config/routes.rb
Rails.application.routes.draw do
  resources :recipes, :only => [:new, :create, :index] do
    member do
      post 'vote_up'

      post 'vote_down'
    end
  end

  root 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :votes

  before_save :set_image_url

  validates :name, :submitter, :url, presence: true
  validates :url, format: { with: URI.regexp }, if: Proc.new { |a| a.url.present? }

  def rank
    votes.ups.count - votes.downs.count
  end

  private

  def set_image_url
    mechanize = Mechanize.new
    if url =~ /allrecipes\.com/
      page = mechanize.get(url)
      self.image_url = page.search("//img[@id='imgPhoto']/@src").text
    elsif url =~ /foodnetworktv\.com/
      page = mechanize.get(url)
      self.image_url = page.search("//div[@class='main-food-image-holder']/img/@src").text
    elsif url =~ /smittenkitchen\.com/
      page = mechanize.get(url)
      self.image_url = page.search("//div[@class='entry']//img").first.search('@src').text
    elsif url =~ /saborintenso\.com/
      page = mechanize.get(url)
      self.image_url = page.search("//div[@id='posts']//div[@align='center']//img/@src").to_a.select{|i| i.to_s =~ /images\/receitas/}.first.text
    elsif url =~ /1001receitas\.com/
      page = mechanize.get(url)
      self.image_url = page.search("//img[@itemprop='photo']/@src").text
    elsif url =~ /lifestyle\.sapo\.pt/
      page = mechanize.get(url)
      self.image_url = page.search("//div[@class='bottom-space thumb']//img/@data-src").text
    elsif url =~ /teleculinaria\.pt/
      page = mechanize.get(url)
      self.image_url = "http://www.teleculinaria.pt" + page.search("//img[@class='ImagemDetalhe ImagemDetalheBIG Traduzir box-sh']/@src").text
    elsif url =~ /myrestaurant\.pt/
      page = mechanize.get(url)
      self.image_url = page.search("//img[@typeof='foaf:Image']/@src").first.text
    elsif url =~ /receitas-de-bacalhau\.info/
      page = mechanize.get(url)
      self.image_url = page.search("//div[@class='post-thumbnail']/img[@class='attachment-post-thumbnail wp-post-image']/@src").text
    elsif url =~ /cincoquartosdelaranja\.com/
      page = mechanize.get(url)
      self.image_url = page.search("//div[@class='post-body entry-content']//img").first.search('@src').text
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :recipe

  validates :recipe, presence: true
  validates :up, inclusion: [true, false]

  scope :ups, -> { where(up: true) }
  scope :downs, -> { where(up: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :vote_up, :vote_down]

  def index
    @recipes = ordered_recipes
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        @recipes = ordered_recipes
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
        format.js   { render :create }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
        format.js   { render :new }
      end
    end
  end

  def vote_up
    previous_votes = []
    previous_votes = JSON.parse(cookies[:votes]) if cookies[:votes]
    unless previous_votes.include?(@recipe.id)
      Vote.create!(recipe: @recipe, up: true)
      cookies[:votes] = JSON.generate(previous_votes << @recipe.id)
    end

    @recipes = ordered_recipes

    respond_to do |format|
      format.html { redirect_to :back }
      format.js   { render 'vote' }
    end
  end

  def vote_down
    previous_votes = []
    previous_votes = JSON.parse(cookies[:votes]) if cookies[:votes]
    unless previous_votes.include?(@recipe.id)
      Vote.create!(recipe: @recipe, up: false)
      cookies[:votes] = JSON.generate(previous_votes << @recipe.id)
    end

    @recipes = ordered_recipes

    respond_to do |format|
      format.html { redirect_to :back }
      format.js   { render 'vote' }
    end
  end

  private
    def ordered_recipes
      @recipes = Recipe.all.sort_by(&:rank).reverse
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :submitter, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def already_voted?(recipe)
    previous_votes = []
    previous_votes = JSON.parse(cookies[:votes]) if cookies[:votes]
    previous_votes.include?(recipe.id)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DinnerChooser</title>
  <link href='http://fonts.googleapis.com/css?family=Mountains+of+Christmas' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_add_recipe.html.erb
<%= link_to 'Add another recipe!', new_recipe_path, remote: true, id: 'add_recipe_link' %>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, remote: true, html: { class: 'pure-form'}) do |f| %>
  <fieldset>
    <legend>Add your favorite Recipe!</legend>

    <input name="recipe[url]" type="url" class="pure-input-2-3" placeholder="http://allrecipes.com/..." required>
  </fieldset>

  <fieldset>
    <input name="recipe[name]" type="text" class="pure-input-1-3" placeholder="Recipe name" required>
    <input name="recipe[submitter]" type="text" class="pure-input-1-3" placeholder="Your name" required>
    <%= submit_tag "Add Recipe!", class: "pure-button pure-button-primary", data: { disable_with: "Please wait..." } %>
  </fieldset>
<% end %>

app/views/recipes/_recipe.html.erb
<tr>
  <td>
    <div class="rank-wrapper">
      <p class="recipe-rank"><%= recipe.rank %></p>
    </div>
  </td>
  <td>
    <div class="image-wrapper">
      <a href="<%= recipe.url %>" title="">
        <img class="recipe-image" src="<%= recipe.image_url %>">
      </a>
    </div>
  </td>
  <td>
    <div class="name-wrapper">
      <%= link_to recipe.name, recipe.url, class: 'recipe-name' %>
    </div>
  </td>
  <td>
    <div class="submitter-wrapper">
      <p class="recipe-submitter"><%= recipe.submitter %></p>
    </div>
  </td>
  <td>
    <div class="vote-wrapper">
      <div class="recipe-vote">
        <% if already_voted? recipe %>
          <i class="fa fa-thumbs-up fa-3 disable"></i>
          <i class="fa fa-thumbs-down fa-3 disable"></i>
        <% else %>
          <%= link_to(vote_up_recipe_path(recipe), remote: true, method: :post) {
            %{<i class="fa fa-thumbs-up fa-3"></i>}.html_safe
          } %>
          <%= link_to(vote_down_recipe_path(recipe), remote: true, method: :post) {
            %{<i class="fa fa-thumbs-down fa-3"></i>}.html_safe
          } %>
        <% end %>
      </div>
    </div>
  </td>
</tr>

app/views/recipes/_recipes.html.erb
<% @recipes.each do |recipe| %>
  <%= render 'recipe', recipe: recipe %>
<% end %>

app/views/recipes/create.js.erb
$('#recipe-rows').html("<%= j (render @recipes) %>");
$('#add-recipe').html('<%= j (render "add_recipe") %>');

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div id="content-wrapper">
  <h1 class="title">What will we have for christmas dinner?</h1>

  <div id="add-recipe">
    <%= render 'add_recipe' %>
  </div>

  <br>

  <table id="recipes-table">
    <thead>
      <tr>
        <th>rank</th>
        <th></th>
        <th>recipe name</th>
        <th>submited by</th>
        <th></th>
      </tr>
    </thead>

    <tbody id="recipe-rows">
      <%= render 'recipes', recipes: @recipes %>
    </tbody>
  </table>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/new.js.erb
$('#add-recipe').html("<%= j (render 'form') %>");

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Submitter:</strong>
  <%= @recipe.submitter %>
</p>

<p>
  <strong>Url:</strong>
  <%= @recipe.url %>
</p>

<%= link_to 'Vote up', vote_up_recipe_path(@recipe), method: :post %> |
<%= link_to 'Vote down', vote_down_recipe_path(@recipe), method: :post %>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/vote.js.erb
$('#recipe-rows').html("<%= j (render @recipes) %>");